jobs:
  - job: DeployNGINX
    pool:
      vmImage: 'ubuntu-latest'  # 사용할 VM 이미지

    steps:
      - checkout: self  # 리포지토리 체크아웃

      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)'  # 소스 폴더
          Contents: 'nginx.conf'  # nginx.conf 파일 포함
          TargetFolder: '/tmp/nginx'  # 임시 경로
          CleanTargetFolder: true

      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)/conf.d'  # 소스 폴더
          Contents: '**'  # 모든 파일 포함
          TargetFolder: '/tmp/nginx/conf.d'  # 임시 경로
          CleanTargetFolder: true

      - task: SSH@0
        inputs:
          sshEndpoint: 'NGINX OSS'  # SSH 연결 설정
          runOptions: 'commands'  # 실행할 옵션
          commands: |
            sudo cp /tmp/nginx/nginx.conf /etc/nginx/nginx.conf  # nginx.conf 복사
            sudo cp -r /tmp/nginx/conf.d/* /etc/nginx/conf.d/  # conf.d 내용 복사
            sudo nginx -s reload  # NGINX 재시작 명령
