pool:
  name: 'Default'

jobs:
  - job: DeployNGINX
    steps:
      - checkout: self

      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            # 이제 비밀번호 없이 실행 가능
            sudo cp -r $(Build.SourcesDirectory)/conf.d/* /etc/nginx/conf.d/
            sudo cp $(Build.SourcesDirectory)/nginx.conf /etc/nginx/
            sudo nginx -t && sudo systemctl reload nginx
        displayName: 'Update NGINX configuration'