pool:
  name: 'Default'

jobs:
  - job: DeployNGINX
    steps:
      - checkout: self

      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            # 백업 생성
            timestamp=$(date +%Y%m%d_%H%M%S)
            sudo cp -r /etc/nginx/conf.d /etc/nginx/conf.d.backup_${timestamp}
            sudo cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.backup_${timestamp}
            
            # conf.d 디렉토리 비우기
            sudo rm -rf /etc/nginx/conf.d/*
            
            # 새 설정 파일 복사
            sudo cp -r $(Build.SourcesDirectory)/conf.d/* /etc/nginx/conf.d/
            sudo cp $(Build.SourcesDirectory)/nginx.conf /etc/nginx/
            
            # 설정 테스트
            if sudo nginx -t; then
              sudo systemctl reload nginx
              echo "NGINX configuration updated successfully"
              
              # 성공 시 이전 백업 삭제 (선택사항)
              sudo rm -rf /etc/nginx/conf.d.backup_${timestamp}
              sudo rm -f /etc/nginx/nginx.conf.backup_${timestamp}
            else
              echo "NGINX configuration test failed, rolling back"
              # 실패 시 롤백
              sudo rm -rf /etc/nginx/conf.d/*
              sudo cp -r /etc/nginx/conf.d.backup_${timestamp}/* /etc/nginx/conf.d/
              sudo cp /etc/nginx/nginx.conf.backup_${timestamp} /etc/nginx/nginx.conf
              exit 1
            fi
        displayName: 'Update NGINX configuration'

      # 선택사항: 현재 설정 파일 목록 출력
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            echo "Current NGINX configuration files:"
            ls -la /etc/nginx/conf.d/
        displayName: 'List current configuration files'