trigger:
  branches:
    include:
      - main  # 변경을 감지할 브랜치

pool:
  name: 'Default'

jobs:
  - job: DeployNGINX
    pool:
      vmImage: 'ubuntu-latest'  # 사용할 VM 이미지

    steps:
      - checkout: self  # 리포지토리 체크아웃

      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)/conf.d'  # 소스 폴더
          Contents: '**'  # 모든 파일 포함
          TargetFolder: '/etc/nginx/conf.d'  # 대상 경로
          CleanTargetFolder: true  # Clean 옵션 추가

      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)'  # nginx.conf 파일이 있는 폴더
          Contents: 'nginx.conf'  # nginx.conf 파일만 포함
          TargetFolder: '/etc/nginx'  # NGINX 설정이 있는 경로
          OverWrite: true

      - script: |
          sudo nginx -s reload
        displayName: 'NGINX 재시작'
