pool:
  name: 'Default'

jobs:
  - job: DeployNGINX
    steps:
      - checkout: self

      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            # conf.d 디렉토리 비우기
            sudo rm -rf /etc/nginx/conf.d/*

            # 새 설정 파일 복사
            sudo cp -r $(Build.SourcesDirectory)/conf.d/* /etc/nginx/conf.d/
            sudo cp $(Build.SourcesDirectory)/nginx.conf /etc/nginx/
            
            # 설정 테스트
            if ! sudo nginx -t; then          
              echo "NGINX configuration test failed"
              exit 1
            fi

            sudo nginx -s reload
            echo "NGINX configuration updated successfully"
        displayName: 'Update NGINX configuration'
